namespace Myriale.Api.Features.SessionExecutions.Contracts;

public sealed record SessionExecutionCapabilities(bool CanRetry, bool CanCancel, bool CanDismiss);

public sealed record SessionExecutionAttemptDiagnosticsResponse(
    string Id,
    int AttemptNumber,
    string Status,
    string? WorkerId,
    string? Provider,
    string? Model,
    string? ProviderRequestId,
    DateTimeOffset StartedAt,
    DateTimeOffset? CompletedAt,
    long? LatencyMilliseconds,
    int? InputTokens,
    int? OutputTokens,
    string? FinishReason,
    string? ErrorCode,
    string? ErrorCategory,
    bool Retryable,
    string? CorrelationId,
    string? TraceId,
    string? SpanId,
    string? ExceptionChain,
    string? RedactedResponseExcerpt,
    string? SentPrompt,
    string? ReceivedResult,
    string? ValidationResult,
    string? PromptVersion,
    string? ContextHash,
    int? ContextSizeBytes);

public sealed record SessionExecutionDiagnosticsResponse(
    string SessionId,
    string TriggerType,
    string TriggerId,
    long Revision,
    string? LeaseOwner,
    string? LeaseTokenHint,
    DateTimeOffset? LeaseExpiresAt,
    IReadOnlyList<SessionExecutionAttemptDiagnosticsResponse> Attempts);

public sealed record SessionExecutionResponse(
    string Id,
    string SessionId,
    string Kind,
    string TriggerType,
    string TriggerId,
    string Status,
    long Revision,
    bool IsRetryable,
    int AttemptCount,
    int MaxAttempts,
    DateTimeOffset? NextAttemptAt,
    string? ErrorCode,
    string? UserErrorMessage,
    DateTimeOffset CreatedAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    DateTimeOffset? CancelRequestedAt,
    DateTimeOffset? DismissedAt,
    SessionExecutionCapabilities Capabilities,
    SessionExecutionDiagnosticsResponse? DevelopmentDiagnostics,
    string? Stage = null,
    int SchemaVersion = 1,
    SessionScenarioTurnProjectionResponse? ScenarioTurn = null,
    string? ActionDecisionAiProfileId = null,
    string? NarrativeAiProfileId = null);
