using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Myriale.Api.Features.Evaluations.Http;

public static class EvaluationEndpoints
{
    public static IEndpointRouteBuilder MapEvaluationEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var sessions = endpoints.MapGroup("/api/evaluation-sessions").WithTags("Evaluation Sessions").RequireCors("MyrialeFrontend").RequireAuthorization();
        sessions.MapGet("", List).WithName("ListEvaluationSessions"); sessions.MapPost("", Create).WithName("CreateEvaluationSession");
        sessions.MapGet("/{id}", Get).WithName("GetEvaluationSession"); sessions.MapPatch("/{id}", Update).WithName("UpdateEvaluationSession");
        sessions.MapPost("/{id}/situations/fixed", AddFixed).WithName("AddFixedEvaluationSituation"); sessions.MapPost("/{id}/situations/quoted", Quote).WithName("QuoteEvaluationSituation");
        sessions.MapDelete("/{id}/situations/{situationId}", DeleteSituation).WithName("DeleteEvaluationSituation"); sessions.MapPost("/{id}/candidates", AddCandidate).WithName("AddEvaluationCandidate");
        sessions.MapPost("/{id}:start", Start).WithName("StartEvaluationSession"); sessions.MapPost("/{id}:cancel", Cancel).WithName("CancelEvaluationSession"); sessions.MapPost("/{id}:retry-failed", Retry).WithName("RetryFailedEvaluationAttempts");
        sessions.MapGet("/{id}/execution", Execution).WithName("GetEvaluationExecution"); sessions.MapGet("/{id}/judgments", Judgments).WithName("GetEvaluationJudgments");
        sessions.MapPost("/{id}/review-batches", CreateReviewBatch).WithName("CreateEvaluationReviewBatch"); sessions.MapPost("/{id}:close-review", CloseReview).WithName("CloseEvaluationReview"); sessions.MapPost("/{id}:reveal-identities", Reveal).WithName("RevealEvaluationIdentities");
        sessions.MapGet("/{id}/results", GetResults).WithName("GetEvaluationResults"); sessions.MapGet("/{id}/exports", Export).WithName("ExportEvaluationSession");
        endpoints.MapGet("/api/evaluation-responses/{id}", RawInvocation).WithName("GetEvaluationRawInvocation").WithTags("Evaluation Sessions").RequireCors("MyrialeFrontend").RequireAuthorization();
        endpoints.MapGet("/api/evaluation-corpora", Corpus).WithName("ListEvaluationCorpora").WithTags("Evaluation Sessions").RequireCors("MyrialeFrontend").RequireAuthorization();
        var reviews = endpoints.MapGroup("/api/evaluation-review-assignments").WithTags("Evaluation Reviews").RequireCors("MyrialeFrontend").RequireAuthorization();
        reviews.MapGet("/{opaqueCode}", Blind).WithName("GetBlindEvaluationAssignment"); reviews.MapPut("/{opaqueCode}/judgments/{itemId}", SaveJudgment).WithName("SaveBlindEvaluationJudgment"); reviews.MapPost("/{opaqueCode}:submit", Submit).WithName("SubmitBlindEvaluationAssignment");
        return endpoints;
    }
    private static async Task<IResult> Create(CreateEvaluationSessionRequest request, ClaimsPrincipal p, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => { var user = User(p); if (user is null) return Results.Unauthorized(); var value = await s.CreateAsync(user.Value, request, ct); return Results.Created($"/api/evaluation-sessions/{value.Summary.Id}", value); });
    private static async Task<IResult> List(ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => User(p) is not { } user ? Results.Unauthorized() : Results.Ok(await s.ListAsync(user, await Admin(p,a), ct));
    private static async Task<IResult> Get(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Owned(await s.GetAsync(User(p)!.Value, await Admin(p,a), id, ct));
    private static async Task<IResult> Update(EvaluationSessionId id, UpdateEvaluationSessionRequest r, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => await Owned(await s.UpdateAsync(User(p)!.Value, await Admin(p,a), id, r, ct)));
    private static async Task<IResult> AddFixed(EvaluationSessionId id, AddFixedEvaluationSituationRequest r, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => await Owned(await s.AddFixedAsync(User(p)!.Value, await Admin(p,a), id, r, ct), created: true));
    private static async Task<IResult> Quote(EvaluationSessionId id, QuoteEvaluationSituationRequest r, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => await Owned(await s.QuoteAsync(User(p)!.Value, await Admin(p,a), id, r, ct), created: true));
    private static async Task<IResult> DeleteSituation(EvaluationSessionId id, EvaluationSituationId situationId, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => (await s.DeleteSituationAsync(User(p)!.Value, await Admin(p,a), id, situationId, ct)) switch { null => Results.NotFound(), false => Results.NotFound(), true => Results.NoContent() });
    private static async Task<IResult> AddCandidate(EvaluationSessionId id, AddEvaluationCandidateRequest r, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => await Owned(await s.AddCandidateAsync(User(p)!.Value, await Admin(p,a), id, r, ct), created: true));
    private static async Task<IResult> Start(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => { var x = await s.StartAsync(User(p)!.Value, await Admin(p,a), id, ct); return x is null ? Results.NotFound() : Results.Accepted($"/api/evaluation-sessions/{id}/execution", x); });
    private static async Task<IResult> Execution(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Owned(await s.ExecutionAsync(User(p)!.Value, await Admin(p,a), id, ct));
    private static async Task<IResult> Cancel(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => (await s.CancelAsync(User(p)!.Value, await Admin(p,a), id, ct)) is null ? Results.NotFound() : Results.Accepted();
    private static async Task<IResult> Retry(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => (await s.RetryFailedAsync(User(p)!.Value, await Admin(p,a), id, ct)) is { } count ? Results.Accepted(value: new { count }) : Results.NotFound());
    private static async Task<IResult> Judgments(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Owned(await s.JudgmentsAsync(User(p)!.Value, await Admin(p,a), id, ct));
    private static async Task<IResult> RawInvocation(EvaluationModelInvocationId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Owned(await s.RawInvocationAsync(User(p)!.Value, await Admin(p,a), await Raw(p,a), id, ct));
    private static IResult Corpus(EvaluationSessionService s) => Results.Ok(new[] { s.Corpus() });
    private static async Task<IResult> CreateReviewBatch(EvaluationSessionId id, CreateEvaluationReviewBatchRequest r, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => (await s.CreateReviewBatchAsync(User(p)!.Value, await Admin(p,a), id, r, ct)) is { } batch ? Results.Created($"/api/evaluation-sessions/{id}/review-batches/{batch}", new { id = batch }) : Results.NotFound());
    private static async Task<IResult> Blind(string opaqueCode, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Owned(await s.BlindAssignmentAsync(User(p)!.Value, await Admin(p,a), opaqueCode, ct));
    private static async Task<IResult> SaveJudgment(string opaqueCode, EvaluationReviewItemId itemId, SaveBlindJudgmentRequest r, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => await Owned(await s.SaveBlindJudgmentAsync(User(p)!.Value, await Admin(p,a), opaqueCode, itemId, r, ct)));
    private static async Task<IResult> Submit(string opaqueCode, long revision, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => (await s.SubmitAssignmentAsync(User(p)!.Value, await Admin(p,a), opaqueCode, revision, ct)) is null ? Results.NotFound() : Results.NoContent());
    private static async Task<IResult> CloseReview(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => (await s.CloseReviewAsync(User(p)!.Value, await Admin(p,a), id, ct)) is null ? Results.NotFound() : Results.NoContent());
    private static async Task<IResult> Reveal(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => (await s.RevealAsync(User(p)!.Value, await Admin(p,a), id, ct)) is null ? Results.NotFound() : Results.NoContent());
    private static async Task<IResult> GetResults(EvaluationSessionId id, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Owned(await s.ResultsAsync(User(p)!.Value, await Admin(p,a), id, ct));
    private static async Task<IResult> Export(EvaluationSessionId id, string? format, bool? redacted, ClaimsPrincipal p, IAuthorizationService a, EvaluationSessionService s, CancellationToken ct) => await Handle(async () => (await s.ExportAsync(User(p)!.Value, await Admin(p,a), await Raw(p,a), id, format ?? "json", redacted ?? true, ct)) is { } file ? Results.File(file.Content, file.ContentType, file.FileName) : Results.NotFound());
    private static async Task<IResult> Handle(Func<Task<IResult>> action) { try { return await action(); } catch (EvaluationValidationException x) { return Results.BadRequest(new EvaluationErrorResponse("Evaluation request is invalid.", x.Code)); } catch (AiProviderException x) { return Results.BadRequest(new EvaluationErrorResponse("AI profile is unavailable.", x.Code)); } catch (DbUpdateConcurrencyException) { return Results.Conflict(new EvaluationErrorResponse("Evaluation revision conflict.", "revision_conflict")); } }
    private static Task<IResult> Owned<T>(T? value, bool created = false) where T : class => Task.FromResult(value is null ? Results.NotFound() : created ? Results.Created(string.Empty, value) : Results.Ok(value));
    private static AccountId? User(ClaimsPrincipal p) => p.FindFirstValue(ClaimTypes.NameIdentifier) is { } id ? new AccountId(id) : null;
    private static async Task<bool> Admin(ClaimsPrincipal p, IAuthorizationService a) => (await a.AuthorizeAsync(p, "Administration")).Succeeded;
    private static async Task<bool> Raw(ClaimsPrincipal p, IAuthorizationService a) => (await a.AuthorizeAsync(p, "EvaluationRawAudit")).Succeeded;
}
