/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ScenariosRouteRouteImport } from './routes/scenarios/route'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as AccountAdminRouteRouteImport } from './routes/account/admin/route'
import { Route as AccountExportRouteImport } from './routes/account/export'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountOauthRouteImport } from './routes/account/oauth'
import { Route as AccountProfileRouteRouteImport } from './routes/account/profile/route'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountWithdrawRouteImport } from './routes/account/withdraw'
import { Route as ModuleExecutionsExecutionIdRouteImport } from './routes/module-executions/$executionId'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios/index'
import { Route as ScenariosNewRouteImport } from './routes/scenarios/new'
import { Route as SessionsSessionIdRouteRouteImport } from './routes/sessions/$sessionId/route'
import { Route as SessionsStartRouteImport } from './routes/sessions/start'
import { Route as AccountAdminAiKeysRouteImport } from './routes/account/admin/ai-keys'
import { Route as AccountAdminAuditLogRouteImport } from './routes/account/admin/audit-log'
import { Route as AccountAdminUsersRouteRouteImport } from './routes/account/admin/users/route'
import { Route as AccountProfileIndexRouteImport } from './routes/account/profile/index'
import { Route as AccountProfileEditRouteImport } from './routes/account/profile/edit'
import { Route as ScenariosScenarioIdEditRouteImport } from './routes/scenarios/$scenarioId/edit'
import { Route as ScenariosScenarioIdRunSettingsRouteImport } from './routes/scenarios/$scenarioId/run-settings'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as SessionsSessionIdModeExceptionRouteImport } from './routes/sessions/$sessionId/mode-exception'
import { Route as SessionsSessionIdNotesRouteImport } from './routes/sessions/$sessionId/notes'
import { Route as SessionsSessionIdPlayRouteImport } from './routes/sessions/$sessionId/play'
import { Route as SessionsSessionIdProgramRouteImport } from './routes/sessions/$sessionId/program'
import { Route as SessionsSessionIdResumeRouteImport } from './routes/sessions/$sessionId/resume'
import { Route as AccountAdminUsersIndexRouteImport } from './routes/account/admin/users/index'
import { Route as AccountAdminUsersUserIdRouteImport } from './routes/account/admin/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRouteRoute = ScenariosRouteRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAdminRouteRoute = AccountAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountExportRoute = AccountExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOauthRoute = AccountOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRouteRoute = AccountProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountWithdrawRoute = AccountWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ModuleExecutionsExecutionIdRoute =
  ModuleExecutionsExecutionIdRouteImport.update({
    id: '/module-executions/$executionId',
    path: '/module-executions/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScenariosRouteRoute,
} as any)
const ScenariosNewRoute = ScenariosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ScenariosRouteRoute,
} as any)
const SessionsSessionIdRouteRoute = SessionsSessionIdRouteRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const SessionsStartRoute = SessionsStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const AccountAdminAiKeysRoute = AccountAdminAiKeysRouteImport.update({
  id: '/ai-keys',
  path: '/ai-keys',
  getParentRoute: () => AccountAdminRouteRoute,
} as any)
const AccountAdminAuditLogRoute = AccountAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AccountAdminRouteRoute,
} as any)
const AccountAdminUsersRouteRoute = AccountAdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AccountAdminRouteRoute,
} as any)
const AccountProfileIndexRoute = AccountProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountProfileRouteRoute,
} as any)
const AccountProfileEditRoute = AccountProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountProfileRouteRoute,
} as any)
const ScenariosScenarioIdEditRoute = ScenariosScenarioIdEditRouteImport.update({
  id: '/$scenarioId/edit',
  path: '/$scenarioId/edit',
  getParentRoute: () => ScenariosRouteRoute,
} as any)
const ScenariosScenarioIdRunSettingsRoute =
  ScenariosScenarioIdRunSettingsRouteImport.update({
    id: '/$scenarioId/run-settings',
    path: '/$scenarioId/run-settings',
    getParentRoute: () => ScenariosRouteRoute,
  } as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRouteRoute,
} as any)
const SessionsSessionIdModeExceptionRoute =
  SessionsSessionIdModeExceptionRouteImport.update({
    id: '/mode-exception',
    path: '/mode-exception',
    getParentRoute: () => SessionsSessionIdRouteRoute,
  } as any)
const SessionsSessionIdNotesRoute = SessionsSessionIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => SessionsSessionIdRouteRoute,
} as any)
const SessionsSessionIdPlayRoute = SessionsSessionIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => SessionsSessionIdRouteRoute,
} as any)
const SessionsSessionIdProgramRoute =
  SessionsSessionIdProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => SessionsSessionIdRouteRoute,
  } as any)
const SessionsSessionIdResumeRoute = SessionsSessionIdResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => SessionsSessionIdRouteRoute,
} as any)
const AccountAdminUsersIndexRoute = AccountAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountAdminUsersRouteRoute,
} as any)
const AccountAdminUsersUserIdRoute = AccountAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AccountAdminUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/scenarios': typeof ScenariosRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/account/admin': typeof AccountAdminRouteRouteWithChildren
  '/account/profile': typeof AccountProfileRouteRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRouteRouteWithChildren
  '/account/export': typeof AccountExportRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth': typeof AccountOauthRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/module-executions/$executionId': typeof ModuleExecutionsExecutionIdRoute
  '/scenarios/new': typeof ScenariosNewRoute
  '/sessions/start': typeof SessionsStartRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/account/admin/users': typeof AccountAdminUsersRouteRouteWithChildren
  '/account/admin/ai-keys': typeof AccountAdminAiKeysRoute
  '/account/admin/audit-log': typeof AccountAdminAuditLogRoute
  '/account/profile/edit': typeof AccountProfileEditRoute
  '/scenarios/$scenarioId/edit': typeof ScenariosScenarioIdEditRoute
  '/scenarios/$scenarioId/run-settings': typeof ScenariosScenarioIdRunSettingsRoute
  '/sessions/$sessionId/mode-exception': typeof SessionsSessionIdModeExceptionRoute
  '/sessions/$sessionId/notes': typeof SessionsSessionIdNotesRoute
  '/sessions/$sessionId/play': typeof SessionsSessionIdPlayRoute
  '/sessions/$sessionId/program': typeof SessionsSessionIdProgramRoute
  '/sessions/$sessionId/resume': typeof SessionsSessionIdResumeRoute
  '/account/profile/': typeof AccountProfileIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/account/admin/users/$userId': typeof AccountAdminUsersUserIdRoute
  '/account/admin/users/': typeof AccountAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/account/admin': typeof AccountAdminRouteRouteWithChildren
  '/account/export': typeof AccountExportRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth': typeof AccountOauthRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/module-executions/$executionId': typeof ModuleExecutionsExecutionIdRoute
  '/scenarios/new': typeof ScenariosNewRoute
  '/sessions/start': typeof SessionsStartRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/account/admin/ai-keys': typeof AccountAdminAiKeysRoute
  '/account/admin/audit-log': typeof AccountAdminAuditLogRoute
  '/account/profile/edit': typeof AccountProfileEditRoute
  '/scenarios/$scenarioId/edit': typeof ScenariosScenarioIdEditRoute
  '/scenarios/$scenarioId/run-settings': typeof ScenariosScenarioIdRunSettingsRoute
  '/sessions/$sessionId/mode-exception': typeof SessionsSessionIdModeExceptionRoute
  '/sessions/$sessionId/notes': typeof SessionsSessionIdNotesRoute
  '/sessions/$sessionId/play': typeof SessionsSessionIdPlayRoute
  '/sessions/$sessionId/program': typeof SessionsSessionIdProgramRoute
  '/sessions/$sessionId/resume': typeof SessionsSessionIdResumeRoute
  '/account/profile': typeof AccountProfileIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/account/admin/users/$userId': typeof AccountAdminUsersUserIdRoute
  '/account/admin/users': typeof AccountAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/scenarios': typeof ScenariosRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/account/admin': typeof AccountAdminRouteRouteWithChildren
  '/account/profile': typeof AccountProfileRouteRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRouteRouteWithChildren
  '/account/export': typeof AccountExportRoute
  '/account/login': typeof AccountLoginRoute
  '/account/oauth': typeof AccountOauthRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/withdraw': typeof AccountWithdrawRoute
  '/module-executions/$executionId': typeof ModuleExecutionsExecutionIdRoute
  '/scenarios/new': typeof ScenariosNewRoute
  '/sessions/start': typeof SessionsStartRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/account/admin/users': typeof AccountAdminUsersRouteRouteWithChildren
  '/account/admin/ai-keys': typeof AccountAdminAiKeysRoute
  '/account/admin/audit-log': typeof AccountAdminAuditLogRoute
  '/account/profile/edit': typeof AccountProfileEditRoute
  '/scenarios/$scenarioId/edit': typeof ScenariosScenarioIdEditRoute
  '/scenarios/$scenarioId/run-settings': typeof ScenariosScenarioIdRunSettingsRoute
  '/sessions/$sessionId/mode-exception': typeof SessionsSessionIdModeExceptionRoute
  '/sessions/$sessionId/notes': typeof SessionsSessionIdNotesRoute
  '/sessions/$sessionId/play': typeof SessionsSessionIdPlayRoute
  '/sessions/$sessionId/program': typeof SessionsSessionIdProgramRoute
  '/sessions/$sessionId/resume': typeof SessionsSessionIdResumeRoute
  '/account/profile/': typeof AccountProfileIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/account/admin/users/$userId': typeof AccountAdminUsersUserIdRoute
  '/account/admin/users/': typeof AccountAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/scenarios'
    | '/sessions'
    | '/admin'
    | '/account/admin'
    | '/account/profile'
    | '/sessions/$sessionId'
    | '/account/export'
    | '/account/login'
    | '/account/oauth'
    | '/account/register'
    | '/account/reset-password'
    | '/account/security'
    | '/account/withdraw'
    | '/module-executions/$executionId'
    | '/scenarios/new'
    | '/sessions/start'
    | '/scenarios/'
    | '/account/admin/users'
    | '/account/admin/ai-keys'
    | '/account/admin/audit-log'
    | '/account/profile/edit'
    | '/scenarios/$scenarioId/edit'
    | '/scenarios/$scenarioId/run-settings'
    | '/sessions/$sessionId/mode-exception'
    | '/sessions/$sessionId/notes'
    | '/sessions/$sessionId/play'
    | '/sessions/$sessionId/program'
    | '/sessions/$sessionId/resume'
    | '/account/profile/'
    | '/sessions/$sessionId/'
    | '/account/admin/users/$userId'
    | '/account/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/sessions'
    | '/admin'
    | '/account/admin'
    | '/account/export'
    | '/account/login'
    | '/account/oauth'
    | '/account/register'
    | '/account/reset-password'
    | '/account/security'
    | '/account/withdraw'
    | '/module-executions/$executionId'
    | '/scenarios/new'
    | '/sessions/start'
    | '/scenarios'
    | '/account/admin/ai-keys'
    | '/account/admin/audit-log'
    | '/account/profile/edit'
    | '/scenarios/$scenarioId/edit'
    | '/scenarios/$scenarioId/run-settings'
    | '/sessions/$sessionId/mode-exception'
    | '/sessions/$sessionId/notes'
    | '/sessions/$sessionId/play'
    | '/sessions/$sessionId/program'
    | '/sessions/$sessionId/resume'
    | '/account/profile'
    | '/sessions/$sessionId'
    | '/account/admin/users/$userId'
    | '/account/admin/users'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/scenarios'
    | '/sessions'
    | '/admin'
    | '/account/admin'
    | '/account/profile'
    | '/sessions/$sessionId'
    | '/account/export'
    | '/account/login'
    | '/account/oauth'
    | '/account/register'
    | '/account/reset-password'
    | '/account/security'
    | '/account/withdraw'
    | '/module-executions/$executionId'
    | '/scenarios/new'
    | '/sessions/start'
    | '/scenarios/'
    | '/account/admin/users'
    | '/account/admin/ai-keys'
    | '/account/admin/audit-log'
    | '/account/profile/edit'
    | '/scenarios/$scenarioId/edit'
    | '/scenarios/$scenarioId/run-settings'
    | '/sessions/$sessionId/mode-exception'
    | '/sessions/$sessionId/notes'
    | '/sessions/$sessionId/play'
    | '/sessions/$sessionId/program'
    | '/sessions/$sessionId/resume'
    | '/account/profile/'
    | '/sessions/$sessionId/'
    | '/account/admin/users/$userId'
    | '/account/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  ScenariosRouteRoute: typeof ScenariosRouteRouteWithChildren
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ModuleExecutionsExecutionIdRoute: typeof ModuleExecutionsExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/admin': {
      id: '/account/admin'
      path: '/admin'
      fullPath: '/account/admin'
      preLoaderRoute: typeof AccountAdminRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/export': {
      id: '/account/export'
      path: '/export'
      fullPath: '/account/export'
      preLoaderRoute: typeof AccountExportRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/oauth': {
      id: '/account/oauth'
      path: '/oauth'
      fullPath: '/account/oauth'
      preLoaderRoute: typeof AccountOauthRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/withdraw': {
      id: '/account/withdraw'
      path: '/withdraw'
      fullPath: '/account/withdraw'
      preLoaderRoute: typeof AccountWithdrawRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/module-executions/$executionId': {
      id: '/module-executions/$executionId'
      path: '/module-executions/$executionId'
      fullPath: '/module-executions/$executionId'
      preLoaderRoute: typeof ModuleExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof ScenariosRouteRoute
    }
    '/scenarios/new': {
      id: '/scenarios/new'
      path: '/new'
      fullPath: '/scenarios/new'
      preLoaderRoute: typeof ScenariosNewRouteImport
      parentRoute: typeof ScenariosRouteRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/sessions/start': {
      id: '/sessions/start'
      path: '/start'
      fullPath: '/sessions/start'
      preLoaderRoute: typeof SessionsStartRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/account/admin/ai-keys': {
      id: '/account/admin/ai-keys'
      path: '/ai-keys'
      fullPath: '/account/admin/ai-keys'
      preLoaderRoute: typeof AccountAdminAiKeysRouteImport
      parentRoute: typeof AccountAdminRouteRoute
    }
    '/account/admin/audit-log': {
      id: '/account/admin/audit-log'
      path: '/audit-log'
      fullPath: '/account/admin/audit-log'
      preLoaderRoute: typeof AccountAdminAuditLogRouteImport
      parentRoute: typeof AccountAdminRouteRoute
    }
    '/account/admin/users': {
      id: '/account/admin/users'
      path: '/users'
      fullPath: '/account/admin/users'
      preLoaderRoute: typeof AccountAdminUsersRouteRouteImport
      parentRoute: typeof AccountAdminRouteRoute
    }
    '/account/profile/': {
      id: '/account/profile/'
      path: '/'
      fullPath: '/account/profile/'
      preLoaderRoute: typeof AccountProfileIndexRouteImport
      parentRoute: typeof AccountProfileRouteRoute
    }
    '/account/profile/edit': {
      id: '/account/profile/edit'
      path: '/edit'
      fullPath: '/account/profile/edit'
      preLoaderRoute: typeof AccountProfileEditRouteImport
      parentRoute: typeof AccountProfileRouteRoute
    }
    '/scenarios/$scenarioId/edit': {
      id: '/scenarios/$scenarioId/edit'
      path: '/$scenarioId/edit'
      fullPath: '/scenarios/$scenarioId/edit'
      preLoaderRoute: typeof ScenariosScenarioIdEditRouteImport
      parentRoute: typeof ScenariosRouteRoute
    }
    '/scenarios/$scenarioId/run-settings': {
      id: '/scenarios/$scenarioId/run-settings'
      path: '/$scenarioId/run-settings'
      fullPath: '/scenarios/$scenarioId/run-settings'
      preLoaderRoute: typeof ScenariosScenarioIdRunSettingsRouteImport
      parentRoute: typeof ScenariosRouteRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/sessions/$sessionId/mode-exception': {
      id: '/sessions/$sessionId/mode-exception'
      path: '/mode-exception'
      fullPath: '/sessions/$sessionId/mode-exception'
      preLoaderRoute: typeof SessionsSessionIdModeExceptionRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/sessions/$sessionId/notes': {
      id: '/sessions/$sessionId/notes'
      path: '/notes'
      fullPath: '/sessions/$sessionId/notes'
      preLoaderRoute: typeof SessionsSessionIdNotesRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/sessions/$sessionId/play': {
      id: '/sessions/$sessionId/play'
      path: '/play'
      fullPath: '/sessions/$sessionId/play'
      preLoaderRoute: typeof SessionsSessionIdPlayRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/sessions/$sessionId/program': {
      id: '/sessions/$sessionId/program'
      path: '/program'
      fullPath: '/sessions/$sessionId/program'
      preLoaderRoute: typeof SessionsSessionIdProgramRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/sessions/$sessionId/resume': {
      id: '/sessions/$sessionId/resume'
      path: '/resume'
      fullPath: '/sessions/$sessionId/resume'
      preLoaderRoute: typeof SessionsSessionIdResumeRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/account/admin/users/': {
      id: '/account/admin/users/'
      path: '/'
      fullPath: '/account/admin/users/'
      preLoaderRoute: typeof AccountAdminUsersIndexRouteImport
      parentRoute: typeof AccountAdminUsersRouteRoute
    }
    '/account/admin/users/$userId': {
      id: '/account/admin/users/$userId'
      path: '/$userId'
      fullPath: '/account/admin/users/$userId'
      preLoaderRoute: typeof AccountAdminUsersUserIdRouteImport
      parentRoute: typeof AccountAdminUsersRouteRoute
    }
  }
}

interface AccountAdminUsersRouteRouteChildren {
  AccountAdminUsersUserIdRoute: typeof AccountAdminUsersUserIdRoute
  AccountAdminUsersIndexRoute: typeof AccountAdminUsersIndexRoute
}

const AccountAdminUsersRouteRouteChildren: AccountAdminUsersRouteRouteChildren =
  {
    AccountAdminUsersUserIdRoute: AccountAdminUsersUserIdRoute,
    AccountAdminUsersIndexRoute: AccountAdminUsersIndexRoute,
  }

const AccountAdminUsersRouteRouteWithChildren =
  AccountAdminUsersRouteRoute._addFileChildren(
    AccountAdminUsersRouteRouteChildren,
  )

interface AccountAdminRouteRouteChildren {
  AccountAdminUsersRouteRoute: typeof AccountAdminUsersRouteRouteWithChildren
  AccountAdminAiKeysRoute: typeof AccountAdminAiKeysRoute
  AccountAdminAuditLogRoute: typeof AccountAdminAuditLogRoute
}

const AccountAdminRouteRouteChildren: AccountAdminRouteRouteChildren = {
  AccountAdminUsersRouteRoute: AccountAdminUsersRouteRouteWithChildren,
  AccountAdminAiKeysRoute: AccountAdminAiKeysRoute,
  AccountAdminAuditLogRoute: AccountAdminAuditLogRoute,
}

const AccountAdminRouteRouteWithChildren =
  AccountAdminRouteRoute._addFileChildren(AccountAdminRouteRouteChildren)

interface AccountProfileRouteRouteChildren {
  AccountProfileEditRoute: typeof AccountProfileEditRoute
  AccountProfileIndexRoute: typeof AccountProfileIndexRoute
}

const AccountProfileRouteRouteChildren: AccountProfileRouteRouteChildren = {
  AccountProfileEditRoute: AccountProfileEditRoute,
  AccountProfileIndexRoute: AccountProfileIndexRoute,
}

const AccountProfileRouteRouteWithChildren =
  AccountProfileRouteRoute._addFileChildren(AccountProfileRouteRouteChildren)

interface AccountRouteRouteChildren {
  AccountAdminRouteRoute: typeof AccountAdminRouteRouteWithChildren
  AccountProfileRouteRoute: typeof AccountProfileRouteRouteWithChildren
  AccountExportRoute: typeof AccountExportRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountOauthRoute: typeof AccountOauthRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountWithdrawRoute: typeof AccountWithdrawRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAdminRouteRoute: AccountAdminRouteRouteWithChildren,
  AccountProfileRouteRoute: AccountProfileRouteRouteWithChildren,
  AccountExportRoute: AccountExportRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountOauthRoute: AccountOauthRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountWithdrawRoute: AccountWithdrawRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface ScenariosRouteRouteChildren {
  ScenariosNewRoute: typeof ScenariosNewRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  ScenariosScenarioIdEditRoute: typeof ScenariosScenarioIdEditRoute
  ScenariosScenarioIdRunSettingsRoute: typeof ScenariosScenarioIdRunSettingsRoute
}

const ScenariosRouteRouteChildren: ScenariosRouteRouteChildren = {
  ScenariosNewRoute: ScenariosNewRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  ScenariosScenarioIdEditRoute: ScenariosScenarioIdEditRoute,
  ScenariosScenarioIdRunSettingsRoute: ScenariosScenarioIdRunSettingsRoute,
}

const ScenariosRouteRouteWithChildren = ScenariosRouteRoute._addFileChildren(
  ScenariosRouteRouteChildren,
)

interface SessionsSessionIdRouteRouteChildren {
  SessionsSessionIdModeExceptionRoute: typeof SessionsSessionIdModeExceptionRoute
  SessionsSessionIdNotesRoute: typeof SessionsSessionIdNotesRoute
  SessionsSessionIdPlayRoute: typeof SessionsSessionIdPlayRoute
  SessionsSessionIdProgramRoute: typeof SessionsSessionIdProgramRoute
  SessionsSessionIdResumeRoute: typeof SessionsSessionIdResumeRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

const SessionsSessionIdRouteRouteChildren: SessionsSessionIdRouteRouteChildren =
  {
    SessionsSessionIdModeExceptionRoute: SessionsSessionIdModeExceptionRoute,
    SessionsSessionIdNotesRoute: SessionsSessionIdNotesRoute,
    SessionsSessionIdPlayRoute: SessionsSessionIdPlayRoute,
    SessionsSessionIdProgramRoute: SessionsSessionIdProgramRoute,
    SessionsSessionIdResumeRoute: SessionsSessionIdResumeRoute,
    SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  }

const SessionsSessionIdRouteRouteWithChildren =
  SessionsSessionIdRouteRoute._addFileChildren(
    SessionsSessionIdRouteRouteChildren,
  )

interface SessionsRouteRouteChildren {
  SessionsSessionIdRouteRoute: typeof SessionsSessionIdRouteRouteWithChildren
  SessionsStartRoute: typeof SessionsStartRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsSessionIdRouteRoute: SessionsSessionIdRouteRouteWithChildren,
  SessionsStartRoute: SessionsStartRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  ScenariosRouteRoute: ScenariosRouteRouteWithChildren,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ModuleExecutionsExecutionIdRoute: ModuleExecutionsExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
